export const guests = [
  { "name": "Magdalena & Jacek Gadowscy", "slug": "magdalena-jacek-gadowscy", lang: "es" },
  { "name": "Luz Lopez & Hernando Barliza", "slug": "luz-hernando-barliza" },
  { "name": "Aniela Gadowska", "slug": "aniela-gadowska" },
  { "name": "Paulina Krych & Piotr Martyka", "slug": "paulina-piotr-martyka" },
  { "name": "Justyna Heinz-Zawalska & Matthias Heinz", "slug": "justyna-matthias-heinz" },
  { "name": "Judyta Janoschka-Bujkowska & Cedric Janoschka", "slug": "judyta-cedric-janoschka" },
  { "name": "Paola Marquez & Martin Gubsch", "slug": "paola-martin-gubsch" },
  { "name": "Julia Landrock & Leonardo Pineda", "slug": "julia-leonardo-pineda" },
  { "name": "Irina Riascos", "slug": "irina-riascos" },
  { "name": "Margarita Morscielo", "slug": "margarita-morscielo" },
  { "name": "Miguel Freyle & Karem Sarmiento", "slug": "miguel-karem-sarmiento" },
  { "name": "Carlos Perez", "slug": "carlos-perez" },
  { "name": "Kevin Castiblanco & Daniela Gaviria", "slug": "kevin-daniela-garcia" },
  { "name": "Luis Avila & Vanessa Cardona", "slug": "luis-vanessa-cardona" },
  { "name": "Raul Lopez", "slug": "raul-lopez" },
  { "name": "Christian Torrico", "slug": "christian-torrico" },
  { "name": "Julia & Wojtek", "slug": "julia-wojtek" },
  { "name": "Ahmed Homudi & Tobias", "slug": "ahmed-tobias" },
  { "name": "Iwona & Paweł Klijewscy", "slug": "iwona-pawel-klijewscy" },
  { "name": "Monika Klijewska", "plusOne": true, "slug": "monika-klijewska" },
  { "name": "Alicja & Jarosław Pol", "slug": "alicja-jaroslaw-pol" },
  { "name": "Agata Pol-Zakręta & Marcin Zakręta", "slug": "agata-marcin-zakreta" },
  { "name": "Małgorzata & Marcin Pol", "slug": "malgorzata-marcin-pol" },
  { "name": "Gabriela Lupa", "plusOne": true, "slug": "gabriela-lupa" },
  { "name": "Barbara Kaczocha & Thomas Feldmeier", "slug": "barbara-thomas-feldmeier" },
  { "name": "Joanna Nawrocka & Paweł Połukord", "slug": "joanna-pawel-polukord" },
  { "name": "Joanna Lawda", "plusOne": true, "slug": "joanna-lawda" },
  { "name": "Sylwestra Koller", "slug": "sylwestra-koller" },
  { "name": "Iwona Parkitna", "slug": "iwona-parkitna" },
  { "name": "Mariola & Marcin Nawroccy", "slug": "mariola-marcin-nawroccy" },
  { "name": "Małgorzata, Zigniew & Jakub Łukowiakowie", "slug": "lukowiakowie" }
]
