export const guests = [
  { "name": "Magdalena & Jacek Gadowscy", "slug": "magdalena-jacek-gadowscy", lang: "es" },
  { "name": "Luz Lopez & Hernando Barliza", "slug": "luz-hernando-barliza", lang: "es" },
  { "name": "Aniela Gadowska", "slug": "aniela-gadowska", lang: "es" },
  { "name": "Paulina Krych & Piotr Martyka", "slug": "paulina-piotr-martyka", lang: "es" },
  { "name": "Justyna Heinz-Zawalska & Matthias Heinz", "slug": "justyna-matthias-heinz", lang: "es" },
  { "name": "Judyta Janoschka-Bujkowska & Cedric Janoschka", "slug": "judyta-cedric-janoschka", lang: "es" },
  { "name": "Paola Marquez & Martin Gubsch", "slug": "paola-martin-gubsch", lang: "es" },
  { "name": "Julia Landrock & Leonardo Pineda", "slug": "julia-leonardo-pineda", lang: "es" },
  { "name": "Irina Riascos", "slug": "irina-riascos", lang: "es" },
  { "name": "Margarita Morscielo", "slug": "margarita-morscielo", lang: "es" },
  { "name": "Miguel Freyle & Karem Sarmiento", "slug": "miguel-karem-sarmiento", lang: "es" },
  { "name": "Carlos Perez", "slug": "carlos-perez", lang: "es" },
  { "name": "Kevin Castiblanco & Daniela Gaviria", "slug": "kevin-daniela-gaviria", lang: "en" },
  { "name": "Luis Avila & Vanessa Cardona", "slug": "luis-vanessa-cardona", lang: "es" },
  { "name": "Raul Lopez", "slug": "raul-lopez", lang: "es" },
  { "name": "Christian Torrico", "slug": "christian-torrico", lang: "es" },
  { "name": "Julia & Wojtek", "slug": "julia-wojtek", lang: "es" },
  { "name": "Ahmed Homudi & Tobias", "slug": "ahmed-tobias", lang: "es" },
  { "name": "Iwona & Paweł Klijewscy", "slug": "iwona-pawel-klijewscy", lang: "es" },
  { "name": "Monika Klijewska", "plusOne": true, "slug": "monika-klijewska", lang: "es" },
  { "name": "Alicja & Jarosław Pol", "slug": "alicja-jaroslaw-pol", lang: "es" },
  { "name": "Agata Pol-Zakręta & Marcin Zakręta", "slug": "agata-marcin-zakreta", lang: "es" },
  { "name": "Małgorzata & Marcin Pol", "slug": "malgorzata-marcin-pol", lang: "es" },
  { "name": "Gabriela Lupa", "plusOne": true, "slug": "gabriela-lupa", lang: "es" },
  { "name": "Barbara Kaczocha & Thomas Feldmeier", "slug": "barbara-thomas-feldmeier", lang: "es" },
  { "name": "Joanna Nawrocka & Paweł Połukord", "slug": "joanna-pawel-polukord", lang: "es" },
  { "name": "Joanna Lawda", "plusOne": true, "slug": "joanna-lawda", lang: "es" },
  { "name": "Sylwestra Koller", "slug": "sylwestra-koller", lang: "es" },
  { "name": "Iwona Parkitna", "slug": "iwona-parkitna", lang: "es" },
  { "name": "Mariola & Marcin Nawroccy", "slug": "mariola-marcin-nawroccy", lang: "es" },
  { "name": "Małgorzata, Zigniew & Jakub Łukowiakowie", "slug": "lukowiakowie", lang: "es" }
]
